### ISSUE TITLE
Updated docs about stopping the queues

### ISSUE THREAD

**Issue by MarcinOrlowski** [Webador/SlmQueue#252]
Documentation shows how to start the queue but I see no word about stopping the queue in the clean way. Can it be added please?

**Comment by MarcinOrlowski** [comment]
Closing as I apparently asked the question in wrong repo.

**Comment by MarcinOrlowski** [comment]
For clarification I went thru [the docs](https://github.com/Webador/SlmQueue/blob/master/docs/5.Workers.md) and from [sources](https://github.com/Webador/SlmQueue/blob/master/src/Worker/AbstractWorker.php#L42) I see that perhaps(?) I should extend [DoctrineWorker](https://github.com/Webador/SlmQueueDoctrine/blob/master/src/Worker/DoctrineWorker.php) and make it conditionally return `ExitWorkerLoopResult`. I am still digging there but but for now that looks bit like overkill and I suspect there's better approach. Any guidance is welcome.

**Comment by basz** [comment]
Register the InterruptStrategy and sent the running process a signal. Eg by pressing control+c.

Any running job will finish and then the worker will exit

**Comment by MarcinOrlowski** [comment]
Thanks, but this would work in my case. I forgot to mention that I run multiple my queues in background (started like `vendor/bin/laminas slm-queue:start myqueue > /dev/null &`) therefore <kbd>CTRL</kbd>+<kbd>C</kbd> is not usable. Also I need stopping to be scripted cannot go that was stopping must be scripted and I got limited possibilities on the deployment machine (i.e. I cannot send any signal via `kill`).

**Comment by basz** [comment]
Usually you would use some process manager like supervisor or docker to run/stop these.

Not sure how you would be able stop them if you run them in the background (with &).

Maybe write a strategy that looks for a special file and if present exit just like the interupt strategy.

**Comment by MarcinOrlowski** [comment]
I figured out clearer (I think) solution - I will inject a high priority job (so it will be picked up next) that only thing in `execute()` would be to return `ExitWorkerLoopResult`. That way should satisfy workers' loop and clearly terminate the worker

**Comment by MarcinOrlowski** [comment]
While I still think the docs should be more clear I solved my problem now. So for future readers: the SLM defaults include  `InterruptStrategy` and that strategy will tell the worker to stop if there's `SIGTERM` or `SIGINT` sent. So all is needed here to properly shut down the worker is a) ensure `InterruptStrategy` is used and then create a job that will send that signal like

```php
class StopQueueWorkerJob extends AbstractJob
{
    public function execute() {
        // Handled by InterruptStrategy.
        \posix_kill(\posix_getpid(), SIGTERM);
    }
}
```

and then enqueue that job (with high priority) in the queue you want to stop.
