### ISSUE TITLE
Beanstalk connection issue

### ISSUE THREAD

**Issue by tapankumar** [Webador/SlmQueue#86]
Hi,

I have followed the provided installation steps and getting below error.

SlmQueue\Queue\QueuePluginManager::get was unable to fetch or create an instance for encodingQueue

Can you please suggest what is wrong with my system?

My composer.json are as below.

"slm/queue": "dev-master",
"slm/queue-beanstalkd": "0.3.*@dev"

Thanks & Regards
Tapan Thapa

**Comment by iit2011081** [comment]
@tapankumar Could you please help me with slm queue? I tried but I think I am doing some silly mistake, When I am pushing a job in the queue it is giving me NULL.

        ```
$response = $queue->push($job);
        var_dump($response); //printing NULL
```
